=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassGeolocation.cities_list.schema.json
{
  "type": "object",
  "required": [
    "count",
    "items",
    "next",
    "page_size",
    "previous",
    "total_pages"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "count": {
      "type": "integer"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "distance",
          "fias_id",
          "has_shop",
          "lat",
          "lon",
          "name",
          "slug"
        ],
        "properties": {
          "distance": {
            "type": "number"
          },
          "fias_id": {
            "type": "string",
            "format": "uuid"
          },
          "has_shop": {
            "type": "boolean"
          },
          "lat": {
            "type": "number"
          },
          "lon": {
            "type": "number"
          },
          "name": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "slug": {
            "type": "string",
            "enum": [
              "armiansk",
              "arkhangelsk",
              "arzamas",
              "arkadak",
              "ardatov",
              "armavir",
              "arsk",
              "ardon",
              "argun",
              "aramil",
              "artemovskii",
              "artemovsk",
              "arsenev",
              "artem"
            ]
          }
        }
      }
    },
    "next": {
      "type": "null"
    },
    "page_size": {
      "type": "integer"
    },
    "previous": {
      "type": "null"
    },
    "total_pages": {
      "type": "integer"
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassGeolocation.cities_list.json
{
  "count": 14,
  "next": null,
  "previous": null,
  "page_size": 30,
  "total_pages": 1,
  "items": [
    {
      "distance": 977150.47594022,
      "has_shop": false,
      "lon": 40.5169606,
      "lat": 64.5394289,
      "fias_id": "06814fb6-0dc3-4bec-ba20-11f894a0faf5",
      "name": "Архангельск",
      "slug": "arkhangelsk"
    },
    {
      "distance": 1142820.62087403,
      "has_shop": true,
      "lon": 43.8408141,
      "lat": 55.3945814,
      "fias_id": "7e42f157-87d6-4111-a406-17432e814723",
      "name": "Арзамас",
      "slug": "arzamas"
    },
    {
      "distance": 1306067.05745153,
      "has_shop": false,
      "lon": 46.2411232,
      "lat": 54.8465544,
      "fias_id": "edab359e-50ac-422a-9117-78ce44b6f758",
      "name": "Ардатов",
      "slug": "ardatov"
    },
    {
      "distance": 1347389.83455199,
      "has_shop": true,
      "lon": 43.4999221,
      "lat": 51.938831,
      "fias_id": "9b58edf4-1ee2-43e0-9df9-d93d48a66ad1",
      "name": "Аркадак",
      "slug": "arkadak"
    },
    {
      "distance": 1452567.58772606,
      "has_shop": true,
      "lon": 49.877067,
      "lat": 56.0912567,
      "fias_id": "d2c6e970-af35-41fe-9ba6-dc44a4187c67",
      "name": "Арск",
      "slug": "arsk"
    },
    {
      "distance": 1522757.01340997,
      "has_shop": false,
      "lon": 33.6910012,
      "lat": 46.1059307,
      "fias_id": "2634dc63-5ab7-4b52-81de-ab6745a8eb02",
      "name": "Армянск",
      "slug": "armiansk"
    },
    {
      "distance": 1860269.94896842,
      "has_shop": true,
      "lon": 41.1324168,
      "lat": 45.0012149,
      "fias_id": "fc9c55d0-c66e-455e-8034-b0944b025c38",
      "name": "Армавир",
      "slug": "armavir"
    },
    {
      "distance": 2053293.77681764,
      "has_shop": true,
      "lon": 60.8343125,
      "lat": 56.694632,
      "fias_id": "c99ffa11-6b7e-4040-9f9e-baa1eeca8a91",
      "name": "Арамиль",
      "slug": "aramil"
    },
    {
      "distance": 2087587.26790506,
      "has_shop": true,
      "lon": 61.8947443,
      "lat": 57.3384177,
      "fias_id": "fdc6b0ad-4096-43e7-a2e9-16404d2e1f68",
      "name": "Артемовский",
      "slug": "artemovskii"
    },
    {
      "distance": 2159248.51344618,
      "has_shop": false,
      "lon": 44.2955775,
      "lat": 43.1755152,
      "fias_id": "fc26547e-11ce-464b-b4f2-96b37df6f23f",
      "name": "Ардон",
      "slug": "ardon"
    },
    {
      "distance": 2212014.12009715,
      "has_shop": false,
      "lon": 45.8723105,
      "lat": 43.2916774,
      "fias_id": "3672454d-2697-4ce1-9666-cc9c744ba5c5",
      "name": "Аргун",
      "slug": "argun"
    },
    {
      "distance": 3973888.16829704,
      "has_shop": false,
      "lon": 93.4358377,
      "lat": 54.3473075,
      "fias_id": "d0d7a2fa-5bdc-4944-8047-75e80e4e883c",
      "name": "Артемовск",
      "slug": "artemovsk"
    },
    {
      "distance": 6763309.81213584,
      "has_shop": false,
      "lon": 133.2696209,
      "lat": 44.1622031,
      "fias_id": "36e4c7ce-7320-48ee-8320-0587c1e09917",
      "name": "Арсеньев",
      "slug": "arsenev"
    },
    {
      "distance": 6787540.18475707,
      "has_shop": false,
      "lon": 132.1596175,
      "lat": 43.3501675,
      "fias_id": "3ce80b09-9b72-4e68-9b2d-becaaee4570e",
      "name": "Артем",
      "slug": "artem"
    }
  ]
}
