=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassCatalog.delivery_search.schema.json
{
  "type": "object",
  "required": [
    "categories",
    "products",
    "query_type",
    "search_query_id"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "categories": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "parent_name",
          "type"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "parent_name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      }
    },
    "detail": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ctx",
          "input",
          "loc",
          "msg",
          "type",
          "url"
        ],
        "properties": {
          "ctx": {
            "type": "object",
            "required": [
              "min_length"
            ],
            "properties": {
              "min_length": {
                "type": "integer"
              }
            }
          },
          "input": {
            "type": "string"
          },
          "loc": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "msg": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "products": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "badges",
          "boost_type",
          "cpd_labels",
          "features",
          "has_age_restriction",
          "image_links",
          "initial_weight_step",
          "is_available",
          "is_large_card",
          "labels",
          "max_qty_per_order",
          "median_price",
          "min_weight",
          "name",
          "orange_loyalty_points",
          "plu",
          "price_piece_unit",
          "prices",
          "product_advert",
          "promo",
          "property_clarification",
          "rating",
          "step",
          "stickers",
          "stock_limit",
          "uom"
        ],
        "properties": {
          "badges": {
            "type": "array",
            "items": {}
          },
          "boost_type": {
            "type": "null"
          },
          "cpd_labels": {
            "type": "null"
          },
          "features": {
            "type": "null"
          },
          "has_age_restriction": {
            "type": "boolean"
          },
          "image_links": {
            "type": "object",
            "required": [
              "normal",
              "small"
            ],
            "properties": {
              "normal": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "small": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          },
          "initial_weight_step": {
            "type": "string"
          },
          "is_available": {
            "type": "boolean"
          },
          "is_large_card": {
            "type": "null"
          },
          "labels": {
            "type": "null"
          },
          "max_qty_per_order": {
            "type": "null"
          },
          "median_price": {
            "type": "null"
          },
          "min_weight": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "orange_loyalty_points": {
            "type": "integer"
          },
          "plu": {
            "type": "integer"
          },
          "price_piece_unit": {
            "type": "null"
          },
          "prices": {
            "type": "object",
            "required": [
              "cpd_promo_price",
              "cpd_promo_price_from_sum_cart",
              "discount",
              "regular"
            ],
            "properties": {
              "cpd_promo_price": {
                "type": "null"
              },
              "cpd_promo_price_from_sum_cart": {
                "type": "null"
              },
              "discount": {
                "type": "null"
              },
              "regular": {
                "type": "string"
              }
            }
          },
          "product_advert": {
            "type": "null"
          },
          "promo": {
            "type": "null"
          },
          "property_clarification": {
            "type": "string"
          },
          "rating": {
            "type": "object",
            "required": [
              "rates_count",
              "rating_average"
            ],
            "properties": {
              "rates_count": {
                "type": "integer"
              },
              "rating_average": {
                "type": "number"
              }
            }
          },
          "step": {
            "type": "string"
          },
          "stickers": {
            "type": "null"
          },
          "stock_limit": {
            "type": "string"
          },
          "uom": {
            "type": "string"
          }
        }
      }
    },
    "query_type": {
      "type": "string"
    },
    "search_query_id": {
      "type": "string",
      "format": "uuid"
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassCatalog.delivery_search.json
{
  "search_query_id": "a64b6301-1fd4-421a-8ffc-89b1fb30387d",
  "query_type": "strict",
  "products": [
    {
      "plu": 4413972,
      "name": "Напиток Добрый Кола пониженной калорийности газированный 1.5л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2035800-main/320x320.jpeg"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2035800-main/800x800.jpeg",
          "https://catalog-images.x5static.net/product/0ec4178ea335c8dfe6f1d80a495e0911-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/666077bdd534eed859b82895324ee017-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/9fb91f819d3de5af2d338178c031ed2c-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 0.0,
        "rates_count": 87
      },
      "promo": null,
      "prices": {
        "regular": "129.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "1.5 л",
      "has_age_restriction": false,
      "stock_limit": "33.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 70,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    }
  ],
  "categories": [
    {
      "id": "264C39231",
      "type": "subcategory",
      "name": "Газированные напитки",
      "parent_name": "Напитки"
    }
  ]
}
