=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassCatalog.delivery_tree.schema.json
{
  "type": "array",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "type": "object",
    "required": [
      "additional_icons",
      "advert",
      "categories",
      "gradient_end",
      "gradient_start",
      "id",
      "image_link",
      "name",
      "products",
      "title_color",
      "type"
    ],
    "properties": {
      "additional_icons": {
        "type": "array",
        "items": {}
      },
      "advert": {
        "type": "null"
      },
      "categories": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "additional_icons",
            "advert",
            "category_type",
            "deeplink",
            "description",
            "gradient_end",
            "gradient_start",
            "id",
            "image_link",
            "image_link_rectangle",
            "name",
            "parent_id",
            "title_color"
          ],
          "properties": {
            "additional_icons": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "type",
                  "url"
                ],
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri"
                  }
                }
              }
            },
            "advert": {
              "type": "null"
            },
            "category_type": {
              "type": "string"
            },
            "deeplink": {
              "type": "null"
            },
            "description": {
              "type": "null"
            },
            "gradient_end": {
              "type": "string"
            },
            "gradient_start": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "image_link": {
              "type": "string",
              "format": "uri"
            },
            "image_link_rectangle": {
              "type": "string",
              "format": "uri"
            },
            "name": {
              "type": "string"
            },
            "parent_id": {
              "type": "null"
            },
            "title_color": {
              "type": "string"
            }
          }
        }
      },
      "gradient_end": {
        "type": "null"
      },
      "gradient_start": {
        "type": "null"
      },
      "id": {
        "type": "string"
      },
      "image_link": {
        "type": "null"
      },
      "name": {
        "type": "string"
      },
      "products": {
        "type": "array",
        "items": {}
      },
      "title_color": {
        "type": "null"
      },
      "type": {
        "type": "string"
      }
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassCatalog.delivery_tree.json
[
  {
    "id": "264C39133",
    "name": "Основной каталог",
    "advert": null,
    "type": "category_list",
    "additional_icons": [],
    "categories": [
      {
        "id": "264C39140",
        "name": "Молочные продукты, яйцо",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39140-icon-chizhik_23cb722548929e3c7817d64bf41a9aa6/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39140-additional-extended-chizhik_98f75071cee7f15a7aec4ea9b878f550/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39140-icon-chizhik_23cb722548929e3c7817d64bf41a9aa6/492x336.png"
      },
      {
        "id": "264C39153",
        "name": "Сыры и масло",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39153-icon-chizhik_4b6b1324ac66c4f81c1218e017317186/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39153-additional-extended-chizhik_8a2c430d22c0c64b451df41d7672b084/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39153-icon-chizhik_4b6b1324ac66c4f81c1218e017317186/492x336.png"
      },
      {
        "id": "264C39160",
        "name": "Крупы и макароны",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39160-icon-chizhik_7487f76684212ae49582de151d7f3195/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39160-additional-extended-chizhik_2fe5e663bfa6ccff8c3a24c57a2cc2e2/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39160-icon-chizhik_7487f76684212ae49582de151d7f3195/492x336.png"
      },
      {
        "id": "264C39166",
        "name": "Хлеб и выпечка",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39166-icon-chizhik_b9f8b48f000fac565022b5b993be2947/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39166-additional-extended-chizhik_6fb9f2401f433265bd1e88901dd686ab/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39166-icon-chizhik_b9f8b48f000fac565022b5b993be2947/492x336.png"
      },
      {
        "id": "264C39172",
        "name": "Масло, соусы, специи",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39172-icon-chizhik_b0996f3d8f6af928b18c607feae1fd68/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39172-additional-extended-chizhik_6fc50c6cd1f2178f027f8e512b6c7f86/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39172-icon-chizhik_b0996f3d8f6af928b18c607feae1fd68/492x336.png"
      },
      {
        "id": "264C39207",
        "name": "Консервация",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39207-icon-chizhik_35f45a116769de25ba4a3fb9d848127b/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39207-additional-extended-chizhik_acae5eee407a7180fd4c6e57634246eb/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39207-icon-chizhik_35f45a116769de25ba4a3fb9d848127b/492x336.png"
      },
      {
        "id": "264C39184",
        "name": "Мясо и птица",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39184-icon-chizhik_4695d4a1e97e349a6130dfcb58c218b2/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39184-additional-extended-chizhik_4a631c5420aae504a3d44be158bc4ce4/312x348.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39184-icon-chizhik_4695d4a1e97e349a6130dfcb58c218b2/492x336.png"
      },
      {
        "id": "264C39179",
        "name": "Мясная гастрономия",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39179-icon-chizhik_da3738229b8d459a550c8cc838f5571a/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39179-additional-extended-chizhik_332c7bd08d4262a7c3c94ba95646db3e/312x348.png"
          },
          {
            "type": "search_tree",
            "url": "https://catalog-images.x5static.net/category/264C39179-additional-search-tree-chizhik_a98d81548a56f7c20d49cd2aa29bd602/144x144.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39179-icon-chizhik_da3738229b8d459a550c8cc838f5571a/492x336.png"
      },
      {
        "id": "264C39189",
        "name": "Рыба и морепродукты",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39189-icon-chizhik_12b7b915ac2f3cf272cda0ded256843a/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39189-additional-extended-chizhik_12d8ff2cf1ec00b693e77f78517100c9/312x348.png"
          },
          {
            "type": "search_tree",
            "url": "https://catalog-images.x5static.net/category/264C39189-additional-search-tree-chizhik_d01d970a4e8b7fde131f0dced0ab6ed6/144x144.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39189-icon-chizhik_12b7b915ac2f3cf272cda0ded256843a/492x336.png"
      },
      {
        "id": "264C39201",
        "name": "Замороженные продукты",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39201-icon-chizhik_5958ded4ddb53da052d6dabf3304e301/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39201-additional-extended-chizhik_c73e8f444cce581de4dfc7256ee04c03/312x348.png"
          },
          {
            "type": "search_tree",
            "url": "https://catalog-images.x5static.net/category/264C39201-additional-search-tree-chizhik_13745c12a8c5adb74baa8a95f2c4ebaa/144x144.png"
          }
        ],
        "deeplink": null,
        "category_type": "default",
        "parent_id": null,
        "description": null,
        "image_link_rectangle": "https://catalog-images.x5static.net/category/264C39201-icon-chizhik_5958ded4ddb53da052d6dabf3304e301/492x336.png"
      },
      {
        "id": "264C39196",
        "name": "Овощи и фрукты",
        "advert": null,
        "image_link": "https://catalog-images.x5static.net/category/264C39196-icon-chizhik_7d33329b1207d7a35593afde1e3eb7d6/345x345.png",
        "gradient_start": "#f7f8fa",
        "gradient_end": "#f7f8fa",
        "title_color": "#302E33",
        "additional_icons": [
          {
            "type": "extended",
            "url": "https://catalog-images.x5static.net/category/264C39196-additional-extended-chizhik_e66c58e2a349048e5950f5365faf593b/312x348.png"
          },
          {
