=== Open-Inflation/chizhik_api/tests/__snapshots__/ProductService.delivery_info.schema.json
{
  "type": "object",
  "required": [
    "attributes",
    "badges",
    "can_view_reviews",
    "cpd_labels",
    "description",
    "description_html",
    "description_md",
    "features",
    "has_age_restriction",
    "image_links",
    "ingredients",
    "ingredients_html",
    "initial_weight_step",
    "is_available",
    "is_marketplace",
    "is_various_manufacturers",
    "labels",
    "marketplace_informer",
    "max_qty_per_order",
    "median_price",
    "min_weight",
    "name",
    "navigation_section",
    "nutrients",
    "orange_loyalty_points",
    "package_quantity",
    "pharmacy",
    "plu",
    "price_piece_unit",
    "price_unit_label",
    "prices",
    "prices_cpd",
    "promo",
    "property_clarification",
    "rating",
    "social_proof",
    "step",
    "stickers",
    "stock_limit",
    "uom"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "uom",
          "value"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "uom": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "value": {
            "type": "string"
          }
        }
      }
    },
    "badges": {
      "type": "array",
      "items": {}
    },
    "can_view_reviews": {
      "type": "boolean"
    },
    "cpd_labels": {
      "type": "null"
    },
    "description": {
      "type": "string"
    },
    "description_html": {
      "type": "null"
    },
    "description_md": {
      "type": "string"
    },
    "features": {
      "type": "null"
    },
    "has_age_restriction": {
      "type": "boolean"
    },
    "image_links": {
      "type": "object",
      "required": [
        "normal",
        "small"
      ],
      "properties": {
        "normal": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          }
        },
        "small": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "ingredients": {
      "type": "string"
    },
    "ingredients_html": {
      "type": "null"
    },
    "initial_weight_step": {
      "type": "string"
    },
    "is_available": {
      "type": "boolean"
    },
    "is_marketplace": {
      "type": "boolean"
    },
    "is_various_manufacturers": {
      "type": "boolean"
    },
    "labels": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "bg_color",
          "label",
          "text_color"
        ],
        "properties": {
          "bg_color": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "text_color": {
            "type": "string"
          }
        }
      }
    },
    "marketplace_informer": {
      "type": "null"
    },
    "max_qty_per_order": {
      "type": "null"
    },
    "median_price": {
      "type": "null"
    },
    "min_weight": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "navigation_section": {
      "type": "null"
    },
    "nutrients": {
      "type": "null"
    },
    "orange_loyalty_points": {
      "type": "null"
    },
    "package_quantity": {
      "type": "null"
    },
    "pharmacy": {
      "type": "null"
    },
    "plu": {
      "type": "integer"
    },
    "price_piece_unit": {
      "type": "null"
    },
    "price_unit_label": {
      "type": "null"
    },
    "prices": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "placement_type",
          "value"
        ],
        "properties": {
          "placement_type": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        }
      }
    },
    "prices_cpd": {
      "type": "null"
    },
    "promo": {
      "type": "null"
    },
    "property_clarification": {
      "type": "string"
    },
    "rating": {
      "type": "object",
      "required": [
        "rates_count",
        "rating_average",
        "reviews_count"
      ],
      "properties": {
        "rates_count": {
          "type": "integer"
        },
        "rating_average": {
          "type": "number"
        },
        "reviews_count": {
          "type": "integer"
        }
      }
    },
    "social_proof": {
      "type": "null"
    },
    "step": {
      "type": "string"
    },
    "stickers": {
      "type": "null"
    },
    "stock_limit": {
      "type": "string"
    },
    "uom": {
      "type": "string"
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ProductService.delivery_info.json
{
  "plu": 4399809,
  "name": "Швабра JB паровая 1300Вт",
  "image_links": {
    "small": [
      "https://catalog-images.x5static.net/product/2113579-main/320x320.jpeg?updated_at=2026-02-02T11:49:29.135Z"
    ],
    "normal": [
      "https://catalog-images.x5static.net/product/2113579-main/800x800.jpeg?updated_at=2026-02-02T11:49:29.135Z",
      "https://catalog-images.x5static.net/product/f99a2b44152a0755babea827a94de240-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/ee87f96f6224148805387bae45d73bfc-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/d058aaf96aef0995b8ca4fe9f94adf45-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/f5315e10778842786958eacf1a1bb5b6-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/4edd1bc5de4266d68a98d73df3039259-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/51cced42758ca782614d795316a260fa-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/88f3893b7981827ddd4181dafcb90ec0-additional/800x800.jpeg",
      "https://catalog-images.x5static.net/product/d8b41c8d54400b0f0b40ecfd7b92e3a8-additional/800x800.jpeg"
    ]
  },
  "uom": "шт",
  "step": "1.0",
  "rating": {
    "rating_average": 0.0,
    "rates_count": 44,
    "reviews_count": 19
  },
  "promo": null,
  "prices": [
    {
      "value": "2099.0",
      "placement_type": "promotional_primary"
    },
    {
      "value": "2999.0",
      "placement_type": "regular_secondary"
    }
  ],
  "labels": [
    {
      "label": "-30%",
      "bg_color": "#FFD700",
      "text_color": "#302E33"
    }
  ],
  "cpd_labels": null,
  "property_clarification": "350 мл",
  "has_age_restriction": true,
  "stock_limit": "19.00",
  "median_price": null,
  "initial_weight_step": "1.0",
  "min_weight": "1.0",
  "max_qty_per_order": null,
  "prices_cpd": null,
  "price_piece_unit": null,
  "description": "Мощность: 1300Вт, объём ёмкости: 350мл, время нагревания: 25сек. Время непрерывной работы: 15 мин. Длина шнура: 4м.",
  "description_md": "Мощность: 1300Вт, объём ёмкости: 350мл, время нагревания: 25сек. Время непрерывной работы: 15 мин. Длина шнура: 4м.",
  "description_html": null,
  "nutrients": null,
  "attributes": [
    {
      "name": "Вес",
      "value": "1.8",
      "uom": "кг"
    },
    {
      "name": "Срок хранения",
      "value": "не ограничен",
      "uom": null
    },
    {
      "name": "Условия хранения",
      "value": "в сухом месте",
      "uom": null
    },
    {
      "name": "Производитель",
      "value": "АО \"Арвиай (Рашен Венчур Инвестментс)\"",
      "uom": null
    },
    {
      "name": "Бренд",
      "value": "JB",
      "uom": null
    },
    {
      "name": "Страна производства",
      "value": "Китай",
      "uom": null
    }
  ],
  "ingredients": "АБС-пластик.",
  "ingredients_html": null,
  "is_available": true,
  "is_various_manufacturers": true,
  "is_marketplace": false,
  "marketplace_informer": null,
  "badges": [],
  "orange_loyalty_points": null,
  "can_view_reviews": false,
  "features": null,
  "pharmacy": null,
  "stickers": null,
  "navigation_section": null,
  "price_unit_label": null,
  "package_quantity": null,
  "social_proof": null
}
