=== Open-Inflation/chizhik_api/tests/__snapshots__/ProductService.info.schema.json
{
  "type": "object",
  "required": [
    "base_unit",
    "categories_tree",
    "description",
    "feedbacks_count",
    "id",
    "images",
    "is_adults",
    "is_favorite",
    "is_inout",
    "meta_data",
    "old_price",
    "plu",
    "price",
    "price_piece_unit",
    "rating",
    "required_ratings",
    "reviews_count",
    "slug",
    "sub_title",
    "title"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "base_unit": {
      "type": "string",
      "enum": [
        "шт"
      ]
    },
    "categories_tree": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "children",
          "depth",
          "icon",
          "id",
          "image",
          "is_adults",
          "is_inout",
          "name",
          "slug"
        ],
        "properties": {
          "children": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "children",
                "depth",
                "icon",
                "id",
                "image",
                "is_adults",
                "is_inout",
                "name",
                "slug"
              ],
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [
                      "children",
                      "depth",
                      "icon",
                      "id",
                      "image",
                      "is_adults",
                      "is_inout",
                      "name",
                      "slug"
                    ],
                    "properties": {
                      "children": {
                        "type": "array",
                        "items": {}
                      },
                      "depth": {
                        "type": "integer"
                      },
                      "icon": {
                        "type": "null"
                      },
                      "id": {
                        "type": "integer"
                      },
                      "image": {
                        "type": "null"
                      },
                      "is_adults": {
                        "type": "boolean"
                      },
                      "is_inout": {
                        "type": "boolean"
                      },
                      "name": {
                        "type": "string",
                        "j2sEnumRejected": true
                      },
                      "slug": {
                        "type": "string",
                        "enum": [
                          "gazirovannye-napitki"
                        ]
                      }
                    }
                  }
                },
                "depth": {
                  "type": "integer"
                },
                "icon": {
                  "type": "string",
                  "format": "uri"
                },
                "id": {
                  "type": "integer"
                },
                "image": {
                  "type": "string",
                  "format": "uri"
                },
                "is_adults": {
                  "type": "boolean"
                },
                "is_inout": {
                  "type": "boolean"
                },
                "name": {
                  "type": "string",
                  "j2sEnumRejected": true
                },
                "slug": {
                  "type": "string",
                  "enum": [
                    "napitki"
                  ]
                }
              }
            }
          },
          "depth": {
            "type": "integer"
          },
          "icon": {
            "type": "null"
          },
          "id": {
            "type": "integer"
          },
          "image": {
            "type": "null"
          },
          "is_adults": {
            "type": "boolean"
          },
          "is_inout": {
            "type": "boolean"
          },
          "name": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "slug": {
            "type": "string",
            "enum": [
              "osnovnoi-katalog"
            ]
          }
        }
      }
    },
    "description": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "feedbacks_count": {
      "type": "integer"
    },
    "id": {
      "type": "integer"
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "image",
          "title"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "image": {
            "type": "string",
            "format": "uri"
          },
          "title": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "is_adults": {
      "type": "boolean"
    },
    "is_favorite": {
      "type": "boolean"
    },
    "is_inout": {
      "type": "boolean"
    },
    "meta_data": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "code",
          "name",
          "value"
        ],
        "properties": {
          "code": {
            "type": "string",
            "enum": [
              "proteins",
              "product_brut_weight",
              "product_net_weight",
              "fats",
              "energy_value",
              "producer_name",
              "brand_name",
              "volume",
              "about_product",
              "composition",
              "exp_date_days",
              "country",
              "temp_storage1",
              "type_package",
              "carboh",
              "plu"
            ]
          },
          "name": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "value": {
            "anyOf": [
              {
                "type": "string",
                "j2sEnumRejected": true
              },
              {
                "type": "number"
              }
            ]
          }
        }
      }
    },
    "old_price": {
      "type": "null"
    },
    "plu": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "price": {
      "type": "number"
    },
    "price_piece_unit": {
      "type": "null"
    },
    "rating": {
      "type": "number"
    },
    "required_ratings": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "reviews_count": {
      "type": "integer"
    },
    "slug": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "sub_title": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "title": {
      "type": "string",
      "j2sEnumRejected": true
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ProductService.info.json
{
  "id": 1055,
  "plu": "4196364",
  "title": "Напиток FUN UP Кола б/алк. 0.5л",
  "sub_title": "",
  "base_unit": "шт",
  "description": "Кола Fun up с сахаром  — классический вкус, не нуждающийся в представлении! В составе нет никаких подсластителей - всё для идеально насыщенного вкуса. Это прекрасный выбор для любителей насладиться знакомым вкусом в любое время дня!",
  "price": 39.0,
  "old_price": null,
  "price_piece_unit": null,
  "rating": 0.0,
  "feedbacks_count": 336,
  "reviews_count": 140,
  "is_inout": false,
  "is_adults": false,
  "is_favorite": false,
  "slug": "napitok-fun-up-kola-balk-05l-1055",
  "images": [
    {
      "id": 38567,
      "title": "",
      "image": "https://chizhik.x5static.net/media/chizhik-assets/product_images/%D0%9D%D0%B0%D0%BF.%D0%B2%D0%BA.%D0%BA%D0%BE%D0%BB%D1%8B_%D0%B1%D0%B0%D0%BB%D0%BA.%D0%B3%D0%B0%D0%B7.%D0%9F%D0%AD%D0%A2_0.5%D0%BB-min.png"
    }
  ],
  "meta_data": [
    {
      "name": "Белки",
      "code": "proteins",
      "value": 0
    },
    {
      "name": "Вес брутто товара, г",
      "code": "product_brut_weight",
      "value": 530
    },
    {
      "name": "Вес нетто продукта, г",
      "code": "product_net_weight",
      "value": 500
    },
    {
      "name": "Жиры",
      "code": "fats",
      "value": 0
    },
    {
      "name": "Ккал",
      "code": "energy_value",
      "value": 43
    },
    {
      "name": "Название производителя",
      "code": "producer_name",
      "value": "ООО \"ЗДОРОВЫЕ ПРОДУКТЫ\""
    },
    {
      "name": "Наименование бренда",
      "code": "brand_name",
      "value": "FUN UP"
    },
    {
      "name": "Объём",
      "code": "volume",
      "value": 0.5
    },
    {
      "name": "О товаре",
      "code": "about_product",
      "value": "Напиток FUN UP со вкусом колы безалкогольный сильногазированный ПЭТ 0.5л"
    },
    {
      "name": "Состав",
      "code": "composition",
      "value": "вода питьевая подготовленная, сахар, ароматизатор натуральный «тип Кола, часть 2» (содержит краситель сахарный колер IV, стабилизатор гуммиарабик), ароматизатор «Кола, часть 1» (содержит регулятор кислотности ортофосфорная кислота, краситель сахарный колер IV, кофеин), регулятор кислотности лимонная кислота, консервант бензоат натрия."
    },
    {
      "name": "Срок годности (в днях)",
      "code": "exp_date_days",
      "value": 276
    },
    {
      "name": "Страна",
      "code": "country",
      "value": "Россия"
    },
    {
      "name": "Температура хранения 1",
      "code": "temp_storage1",
      "value": "0 - +25"
    },
    {
      "name": "Тип упаковки",
      "code": "type_package",
      "value": "ПЭТ"
    },
    {
      "name": "Углеводы",
      "code": "carboh",
      "value": 10.8
    },
    {
      "name": "Артикул",
      "code": "plu",
      "value": "4196364"
    }
  ],
  "categories_tree": [
    {
      "id": 133,
      "name": "Основной каталог",
      "image": null,
      "icon": null,
      "depth": 1,
      "is_adults": false,
      "is_inout": false,
      "slug": "osnovnoi-katalog",
      "children": [
        {
          "id": 54,
          "name": "Напитки",
          "image": "https://chizhik.x5static.net/media/chizhik-assets/categories/%D0%9D%D0%B0%D0%BF%D0%B8%D1%82%D0%BA%D0%B8.png",
          "icon": "https://chizhik.x5static.net/media/chizhik-assets/categories/icon/Type%D0%AD%D0%92-min.png",
          "depth": 2,
          "is_adults": false,
          "is_inout": false,
          "slug": "napitki",
          "children": [
            {
              "id": 56,
              "name": "Газированные напитки",
              "image": null,
              "icon": null,
              "depth": 3,
              "is_adults": false,
              "is_inout": false,
              "slug": "gazirovannye-napitki",
              "children": []
            }
          ]
        }
      ]
    }
  ],
  "required_ratings": [
    1,
    2,
    3
  ]
}
