=== Open-Inflation/chizhik_api/tests/__snapshots__/ShopService.all.schema.json
{
  "type": "array",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "type": "object",
    "required": [
      "average_rating",
      "id",
      "is_nearest",
      "lat",
      "locality",
      "lon",
      "name",
      "open_date",
      "sap_id",
      "slug",
      "status",
      "working_hours"
    ],
    "properties": {
      "average_rating": {
        "type": "number"
      },
      "id": {
        "type": "integer"
      },
      "is_nearest": {
        "type": "boolean"
      },
      "lat": {
        "type": "number"
      },
      "locality": {
        "type": "string"
      },
      "lon": {
        "type": "number"
      },
      "name": {
        "type": "string"
      },
      "open_date": {
        "type": "string",
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "string",
            "format": "date"
          }
        ]
      },
      "sap_id": {
        "type": "string"
      },
      "slug": {
        "type": "string"
      },
      "status": {
        "type": "integer"
      },
      "working_hours": {
        "type": "string"
      }
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ShopService.search.json
[
  {
    "id": 34907,
    "sap_id": "HAOJ",
    "lon": 37.56468447,
    "lat": 55.88091555,
    "status": 1,
    "name": "Москва, 800-летия Москвы ул, Дом 11",
    "is_nearest": false,
    "slug": "moskva-800-letiia-11-34907",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 3.2,
    "locality": "Москва",
    "open_date": "2024-07-31"
  },
  {
    "id": 36051,
    "sap_id": "HAWG",
    "lon": 37.82568255,
    "lat": 55.81187834,
    "status": 1,
    "name": "Москва, Щёлковское ш, Дом 94",
    "is_nearest": false,
    "slug": "moskva-shchiolkovskoe94-11-36051",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.1,
    "locality": "Москва",
    "open_date": "2024-09-30"
  },
  {
    "id": 35314,
    "sap_id": "HARJ",
    "lon": 37.52302356,
    "lat": 55.60377156,
    "status": 1,
    "name": "Москва, Вильнюсская ул, Дом 5",
    "is_nearest": false,
    "slug": "moskva-vilniusskaia-5-35314",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.2,
    "locality": "Москва",
    "open_date": "2024-08-27"
  },
  {
    "id": 39675,
    "sap_id": "HBN1",
    "lon": 37.83912563,
    "lat": 55.7584225,
    "status": 1,
    "name": "Москва, Сталеваров ул, Дом 14, Корпус 1",
    "is_nearest": false,
    "slug": "moskva-stalevarov-14k1-39675",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 5.0,
    "locality": "Москва",
    "open_date": "2025-12-31"
  },
  {
    "id": 33149,
    "sap_id": "HABX",
    "lon": 37.76072353,
    "lat": 55.65632706,
    "status": 1,
    "name": "Москва, Братиславская ул, Дом 20",
    "is_nearest": false,
    "slug": "moskva-bratislavskaia-20-33149",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.2,
    "locality": "Москва",
    "open_date": "2023-12-08"
  },
  {
    "id": 42806,
    "sap_id": "HC3U",
    "lon": 37.35768964,
    "lat": 55.84689227,
    "status": 1,
    "name": "Москва, Митинская ул, Дом 29",
    "is_nearest": false,
    "slug": "mitino-mitinskaia-29-42806",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 0.0,
    "locality": "Москва",
    "open_date": "2026-01-31"
  },
  {
    "id": 32833,
    "sap_id": "HA9J",
    "lon": 37.6092259,
    "lat": 55.60092599,
    "status": 1,
    "name": "Москва, Россошанский проезд, Дом 3",
    "is_nearest": false,
    "slug": "moskva-rossoshanskii-3-32833",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.1,
    "locality": "Москва",
    "open_date": "2023-12-21"
  },
  {
    "id": 30357,
    "sap_id": "HDQB",
    "lon": 37.82188369,
    "lat": 55.71609717,
    "status": 1,
    "name": "Москва, Вешняковская ул, Дом 43",
    "is_nearest": false,
    "slug": "moskva-veshniakovskaia-43-30357",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.0,
    "locality": "Москва",
    "open_date": "2023-07-23"
  },
  {
    "id": 29756,
    "sap_id": "HDKU",
    "lon": 37.83092821,
    "lat": 55.78113362,
    "status": 1,
    "name": "Москва, Чечулина ул, Дом 18",
    "is_nearest": false,
    "slug": "moskva-chechulina-18-29756",
    "working_hours": "с 09:30 до 21:30",
    "average_rating": 4.0,
    "locality": "Москва",
    "open_date": "2023-03-29"
  },
  {
    "id": 26793,
    "sap_id": "HDAB",
    "lon": 37.34714194,
    "lat": 55.64588372,
    "status": 1,
    "name": "Москва, Чоботовская ул, Дом 19, Сооружение 1",
    "is_nearest": false,
    "slug": "moskva-chobotovskaia-19s1-26793",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 3.4,
    "locality": "Москва",
    "open_date": "2022-03-31"
  },
  {
    "id": 27698,
    "sap_id": "HD8K",
    "lon": 37.78854346,
    "lat": 55.74344224,
    "status": 1,
    "name": "Москва, Кусковская ул, Дом 37/60",
    "is_nearest": false,
    "slug": "moskva-kuskovskaia-3760-27698",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.0,
    "locality": "Москва",
    "open_date": "2022-09-19"
  },
  {
    "id": 27385,
    "sap_id": "HD4W",
    "lon": 37.78814757,
    "lat": 55.7210735,
    "status": 1,
    "name": "Москва, Паперника ул, Дом 13",
    "is_nearest": false,
    "slug": "moskva-papernika-13-27385",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.3,
    "locality": "Москва",
    "open_date": "2022-07-31"
  },
  {
    "id": 31266,
    "sap_id": "HDWD",
    "lon": 37.37833956,
    "lat": 55.53242954,
    "status": 1,
    "name": "Москва, Мостовая ул, Дом 5, Корпус 2",
    "is_nearest": false,
    "slug": "msk-desenovskoemostovaia-31266",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.6,
    "locality": "Москва",
    "open_date": "2023-07-31"
  },
  {
    "id": 35439,
    "sap_id": "HASI",
    "lon": 37.76182093,
    "lat": 55.8268378,
    "status": 1,
    "name": "Москва, Открытое ш, Дом 25, Корпус 2",
    "is_nearest": false,
    "slug": "moskva-otkrytoe-sh-25k2-35439",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 3.4,
    "locality": "Москва",
    "open_date": "2024-07-22"
  },
  {
    "id": 31730,
    "sap_id": "HA0U",
    "lon": 37.63834763,
    "lat": 55.71033483,
    "status": 1,
    "name": "Москва, Даниловская наб, Дом 8, Строение 4",
    "is_nearest": false,
    "slug": "moskva-danilovskaia-8s4-31730",
    "working_hours": "с 10:00 до 22:00",
    "average_rating": 4.1,
    "locality": "Москва",
    "open_date": "2021-12-30"
  },
  {
    "id": 26504,
    "sap_id": "HD87",
    "lon": 37.83372708,
    "lat": 55.76833314,
    "status": 1,
    "name": "Москва, Саянская ул, Дом 11Б",
    "is_nearest": false,
    "slug": "moskva-saianskaia-11b-26504",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 3.4,
    "locality": "Москва",
    "open_date": "2022-03-28"
  },
  {
    "id": 27544,
    "sap_id": "HD6L",
    "lon": 37.59417711,
    "lat": 55.88991532,
    "status": 1,
    "name": "Москва, Пришвина ул, Дом 3Г",
    "is_nearest": false,
    "slug": "moskva-prishvina3g-27544",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.2,
    "locality": "Москва",
    "open_date": "2022-09-12"
  },
  {
    "id": 35025,
    "sap_id": "HAPM",
    "lon": 37.69531044,
    "lat": 55.86091754,
    "status": 1,
    "name": "Москва, Ярославское ш, Дом 30",
    "is_nearest": false,
    "slug": "moskva-iaroslavskoe-30-35025",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.4,
    "locality": "Москва",
    "open_date": "2024-09-30"
  },
  {
    "id": 31719,
    "sap_id": "HA0O",
    "lon": 37.66569244,
    "lat": 55.58934799,
    "status": 1,
    "name": "Москва, Бирюлёвская ул, Дом 37А",
    "is_nearest": false,
    "slug": "moskva-biriulevskaia-37a-31719",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.2,
    "locality": "Москва",
    "open_date": "2021-12-02"
  },
  {
    "id": 31986,
    "sap_id": "HA29",
    "lon": 37.54632001,
    "lat": 55.64672391,
    "status": 1,
    "name": "Москва, Введенского ул, Дом 3, Корпус 6",
    "is_nearest": false,
    "slug": "moskva-vvedenskogo-3-31986",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 3.7,
    "locality": "Москва",
    "open_date": "2023-10-31"
  },
  {
    "id": 27924,
    "sap_id": "HDBM",
    "lon": 37.68636249,
    "lat": 55.87037216,
    "status": 1,
    "name": "Москва, Коминтерна ул, Дом 15",
    "is_nearest": false,
    "slug": "moskva-kominterna-15-27924",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.6,
    "locality": "Москва",
    "open_date": "2022-12-22"
  },
  {
    "id": 34241,
    "sap_id": "HAKL",
    "lon": 37.35948328,
    "lat": 55.78358855,
    "status": 1,
    "name": "Москва, Обводное ш, Дом 7",
    "is_nearest": false,
    "slug": "moskva-obvodnoe7-34241",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.5,
    "locality": "Москва",
    "open_date": "2024-05-26"
  },
  {
    "id": 30164,
    "sap_id": "HDOP",
    "lon": 37.66253079,
    "lat": 55.89351923,
    "status": 1,
    "name": "Москва, Студёный проезд, Владение 7А",
    "is_nearest": false,
    "slug": "moskva-studionyi-7a-30164",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.5,
    "locality": "Москва",
    "open_date": "2023-04-28"
  },
  {
    "id": 32042,
    "sap_id": "HA2Q",
    "lon": 37.40552763,
    "lat": 55.42098142,
    "status": 1,
    "name": "Щапово п, Дом 69А, Строение 4",
    "is_nearest": false,
    "slug": "shchapovo-69a-32042",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.3,
    "locality": "Щапово п",
    "open_date": "2023-12-30"
  },
  {
    "id": 34952,
    "sap_id": "HAOV",
    "lon": 37.65404293,
    "lat": 55.6236361,
    "status": 1,
    "name": "Москва, Севанская ул, Дом 15, Корпус 1",
    "is_nearest": false,
    "slug": "moskva-sevanskaia-15-34952",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 3.6,
    "locality": "Москва",
    "open_date": "2024-05-28"
  },
  {
    "id": 33400,
    "sap_id": "HAED",
    "lon": 37.61609257,
    "lat": 55.62759831,
    "status": 1,
    "name": "Москва, Варшавское ш, Дом 124, Корпус 1",
    "is_nearest": false,
    "slug": "moskva-varshavskoe-124k1-33400",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.3,
    "locality": "Москва",
    "open_date": "2023-12-28"
  },
  {
    "id": 37455,
    "sap_id": "HB79",
    "lon": 37.72183308,
    "lat": 55.62568689,
    "status": 1,
    "name": "Москва, Борисовский проезд, Дом 14, Корпус 1",
    "is_nearest": false,
    "slug": "moskva-borisovskii-14-37455",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 5.0,
    "locality": "Москва",
    "open_date": "2025-08-30"
  },
  {
    "id": 27164,
    "sap_id": "HD2O",
    "lon": 37.70794712,
    "lat": 55.87424625,
    "status": 1,
    "name": "Москва, Палехская ул, Дом 131А",
    "is_nearest": false,
    "slug": "moskva-palekhskaia-131a-27164",
    "working_hours": "с 09:00 до 21:00",
    "average_rating": 4.0,
    "locality": "Москва",
    "open_date": "2022-06-20"
  },
  {
    "id": 40055,
    "sap_id": "HBPM",
    "lon": 37.65194508,
