=== Open-Inflation/chizhik_api/tests/__snapshots__/unstandard_urls.schema.json
{
  "type": "object",
  "required": [
    "https://app.chizhik.club/api/v1",
    "https://app.chizhik.club/api/v1/catalog/unauthorized/active_inout/",
    "https://app.chizhik.club/api/v1/catalog/unauthorized/categories/",
    "https://app.chizhik.club/api/v1/catalog/unauthorized/products/1055/",
    "https://app.chizhik.club/api/v1/catalog/unauthorized/products/?page=1&category_id=133&term=%D0%BA%D0%BE%D0%BB%D0%B0",
    "https://app.chizhik.club/api/v1/geo/cities/",
    "https://app.chizhik.club/api/v1/geo/cities/?name=%D0%B0%D1%80&page=1",
    "https://app.chizhik.club/api/v1/geo/cities/?utm_referrer=https%3a%2f%2fchizhik.club%2f",
    "https://app.chizhik.club/api/v1/services/ping/",
    "https://app.chizhik.club/api/v1/services/ping/?utm_referrer=https%3a%2f%2fchizhik.club%2f",
    "https://app.chizhik.club/api/v1/shops",
    "https://app.chizhik.club/api/v1/shops/",
    "https://app.chizhik.club/api/v1/shops/?term=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0",
    "https://app.chizhik.club/api/v1/shops?term=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "https://app.chizhik.club/api/v1": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "sec-fetch-user",
        "upgrade-insecure-requests",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "sec-fetch-user": {
          "type": "string"
        },
        "upgrade-insecure-requests": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/catalog/unauthorized/active_inout/": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/catalog/unauthorized/categories/": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/catalog/unauthorized/products/1055/": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/catalog/unauthorized/products/?page=1&category_id=133&term=%D0%BA%D0%BE%D0%BB%D0%B0": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/geo/cities/": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "host",
        "origin",
        "referer",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "origin": {
          "type": "string",
          "format": "uri"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/geo/cities/?name=%D0%B0%D1%80&page=1": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/geo/cities/?utm_referrer=https%3a%2f%2fchizhik.club%2f": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "host",
        "origin",
        "referer",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "origin": {
          "type": "string",
          "format": "uri"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/services/ping/": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "host",
        "origin",
        "referer",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "origin": {
          "type": "string",
          "format": "uri"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/services/ping/?utm_referrer=https%3a%2f%2fchizhik.club%2f": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "host",
        "origin",
        "referer",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "origin": {
          "type": "string",
          "format": "uri"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/shops": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/shops/": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/shops/?term=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "user-agent": {
          "type": "string"
        }
      }
    },
    "https://app.chizhik.club/api/v1/shops?term=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0": {
      "type": "object",
      "required": [
        "accept",
        "accept-encoding",
        "accept-language",
        "connection",
        "cookie",
        "host",
        "referer",
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "user-agent"
      ],
      "properties": {
        "accept": {
          "type": "string"
        },
        "accept-encoding": {
          "type": "string"
        },
        "accept-language": {
          "type": "string"
        },
        "connection": {
          "type": "string"
        },
        "cookie": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "referer": {
          "type": "string",
          "format": "uri"
        },
        "sec-fetch-dest": {
          "type": "string"
        },
        "sec-fetch-mode": {
          "type": "string"
        },
        "sec-fetch-site": {
          "type": "string"
        },
        "user-agent": {
          "type": "string"
        }
      }
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/unstandard_urls.json
{
  "https://app.chizhik.club/api/v1/services/ping/": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "origin": "https://chizhik.club",
    "referer": "https://chizhik.club/",
    "connection": "keep-alive"
  },
  "https://app.chizhik.club/api/v1/services/ping/?utm_referrer=https%3a%2f%2fchizhik.club%2f": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "origin": "https://chizhik.club",
    "referer": "https://chizhik.club/",
    "connection": "keep-alive"
  },
  "https://app.chizhik.club/api/v1/geo/cities/": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "origin": "https://chizhik.club",
    "referer": "https://chizhik.club/",
    "connection": "keep-alive"
  },
  "https://app.chizhik.club/api/v1/geo/cities/?utm_referrer=https%3a%2f%2fchizhik.club%2f": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "origin": "https://chizhik.club",
    "referer": "https://chizhik.club/",
    "connection": "keep-alive"
  },
  "https://app.chizhik.club/api/v1": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "connection": "keep-alive",
    "cookie": "spjs=1774778547689_2cfd8515_013525df_6622b9ae79cabdb51ff75aea00cbf496_c0xZSITEeI/aq35HE2K0gKoK2HUeQVQsqChtRA5ho+p3VnrTnm+8CbSFKcENZkCpdHN33hB7LiaCImfBKcidpdEh1JwYebIjvo9TyxfG6gJPonHotUW5AfyM8EkzwzeOewp+x7JCtgz5+f1UnpCHLhiF/fDsPHB88JUsIT7L4spDd/tTn08DEYAwISwJ6T2V0afUzZ1JXATRIHZMVs1Lk98v0Mz1QFlCTr5CD0f3y7NPaOzBhSAUnfmZWCAnp6a+CnuK1R8QJqlnKZtyHr8zyFZ3W8eu7nJrhyI+dgjY7MEAEXWtDExoY/IiBn57m7+iBhzg6LcHuwPer/JJt+aqFwt/o4sSd25MTehpdGGBxd0cOq7W4gcTL77+H0IMa5GIERW5UZhdVCpWNi9yGorzGzIQ5Ly9WHyVpMHlKDqa68GBIPaIjWgpo78vYksHZrsrbg17iTTAfdYrCuaO1fFE3bgo/EJEdACbPu+Kc5NSsBq/Ya0Bm7klONJTSEef7qKLtjercptLU6TAkCWsGHi68AQXQz9qSj4X06NnTwXj3RR5eJQ9FJUpMo9Oc2k15BogXwt7EYVXoemc/L3nMUHj27v9qfWwNmLpAvJKYzi4VopShfzh3e0gCIEEWMA967kmIDHl3Yl5LVaC8iZeS7vv1wN8oJjENGgV3qnSQjX1sKFNbHDJlG4YHp89mAFEILJYTBv5MKNktw/Lqp9XRU+nq9X32oIef7N49cX5UBz9Mil0Q3fem2q+5/Jy9k+WFkJ6rt8LM2eYLSMPL3LE6RlFfaHSDjZldBlAXL3y+ZNBt43bIf7WsEX2rem5fUQYIDatODfL079PI0qWtmpSDe2RiRUE6OCfnAKmo6N3TxravoZSIfXNmWk9NMCgZEwX14uAf85yu5Y3unPd/n1XuPhIE/zrL8eTZzZe2qJ9t5H1lctOf7owsKcSffUkeYEd7HCJVLHZxb1pkbhUtXhBm+m3F9Gi9Gz65Q5kUaNVfQj4viSQr/LLluc5AtwucUoW5bohHazxyJBkPI/eq0xjYkAmDlsp/EWTYTeM26h/xBvvtwtSJv9ivF0UCdMlfkEbbLiIRCt335JrLwfdY3RvSUmI0BUR1JrOiulW7g8FrEAw7aTIH3HKMQWY8FCsoUXDYjuPiScuRDN08Bs/7ktzB+bmW18BbRWISKIrtip6kxF9wFlVKXyCzGg3I5Evd5wSij8mwqB0zBi5PQzTUnSINrabsX8982qkxikT/b5zwBT3GJBIC/tj4+FmLviqb+axab2FUSp9yi5iFoh0hxvDH+6zCkWFrccaKnYM2GRdT+v+H0fTI/bPGmg+B1GidUs4SGah+uvCm5dqvyRVMbbfGYl22sMPxRiaZkxZ0htZ5xXDv/LP6e0EY+Iz0np1nJvWIlQoR66aczyusgjVpPlTF8DfBQRxdwybz5+AhECjGysv62BxpCLarP7bRYlpc02W4bqF3i; spsc=1774778547689_6382028ec113c3b4605ecf0f0fbf0adc_fZg33dK9zOBI2XTd1-6.XCalEAjqkh679j-gWiugCNcZ; spid=1774778547689_539c201fef3bfae362bb1ce15d5f0a3b_lpi4dwvj7l2eo49g; TS01418b58=0147334a4a22290f6cda4302f7d16b912b7d50ed310ab10a37037f8f2de846e9548f3c6562d63c22b233b66cabaa2673e92fd42df7; _ym_uid=1774778556178935838; _ym_d=1774778556; TS01eb8238=0147334a4abfac71489237665b6e028759c2367d3adaf5d3be6242f2970a38eb64abf058f9ebcf3018f05090d7e58b59b7f1fb5e7a; TS01eb8238028=015905a0a529baaaecec5db2c4c35a8f4bbaf80bd5a456c294b297841131fff871cd5030cd61dd008dc32abaf9dc22f21f262ad1c8",
    "upgrade-insecure-requests": "1",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "none",
    "sec-fetch-user": "?1"
  },
  "https://app.chizhik.club/api/v1/catalog/unauthorized/active_inout/": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "referer": "https://app.chizhik.club/api/v1",
    "connection": "keep-alive",
    "cookie": "spjs=1774778547689_2cfd8515_013525df_6622b9ae79cabdb51ff75aea00cbf496_c0xZSITEeI/aq35HE2K0gKoK2HUeQVQsqChtRA5ho+p3VnrTnm+8CbSFKcENZkCpdHN33hB7LiaCImfBKcidpdEh1JwYebIjvo9TyxfG6gJPonHotUW5AfyM8EkzwzeOewp+x7JCtgz5+f1UnpCHLhiF/fDsPHB88JUsIT7L4spDd/tTn08DEYAwISwJ6T2V0afUzZ1JXATRIHZMVs1Lk98v0Mz1QFlCTr5CD0f3y7NPaOzBhSAUnfmZWCAnp6a+CnuK1R8QJqlnKZtyHr8zyFZ3W8eu7nJrhyI+dgjY7MEAEXWtDExoY/IiBn57m7+iBhzg6LcHuwPer/JJt+aqFwt/o4sSd25MTehpdGGBxd0cOq7W4gcTL77+H0IMa5GIERW5UZhdVCpWNi9yGorzGzIQ5Ly9WHyVpMHlKDqa68GBIPaIjWgpo78vYksHZrsrbg17iTTAfdYrCuaO1fFE3bgo/EJEdACbPu+Kc5NSsBq/Ya0Bm7klONJTSEef7qKLtjercptLU6TAkCWsGHi68AQXQz9qSj4X06NnTwXj3RR5eJQ9FJUpMo9Oc2k15BogXwt7EYVXoemc/L3nMUHj27v9qfWwNmLpAvJKYzi4VopShfzh3e0gCIEEWMA967kmIDHl3Yl5LVaC8iZeS7vv1wN8oJjENGgV3qnSQjX1sKFNbHDJlG4YHp89mAFEILJYTBv5MKNktw/Lqp9XRU+nq9X32oIef7N49cX5UBz9Mil0Q3fem2q+5/Jy9k+WFkJ6rt8LM2eYLSMPL3LE6RlFfaHSDjZldBlAXL3y+ZNBt43bIf7WsEX2rem5fUQYIDatODfL079PI0qWtmpSDe2RiRUE6OCfnAKmo6N3TxravoZSIfXNmWk9NMCgZEwX14uAf85yu5Y3unPd/n1XuPhIE/zrL8eTZzZe2qJ9t5H1lctOf7owsKcSffUkeYEd7HCJVLHZxb1pkbhUtXhBm+m3F9Gi9Gz65Q5kUaNVfQj4viSQr/LLluc5AtwucUoW5bohHazxyJBkPI/eq0xjYkAmDlsp/EWTYTeM26h/xBvvtwtSJv9ivF0UCdMlfkEbbLiIRCt335JrLwfdY3RvSUmI0BUR1JrOiulW7g8FrEAw7aTIH3HKMQWY8FCsoUXDYjuPiScuRDN08Bs/7ktzB+bmW18BbRWISKIrtip6kxF9wFlVKXyCzGg3I5Evd5wSij8mwqB0zBi5PQzTUnSINrabsX8982qkxikT/b5zwBT3GJBIC/tj4+FmLviqb+axab2FUSp9yi5iFoh0hxvDH+6zCkWFrccaKnYM2GRdT+v+H0fTI/bPGmg+B1GidUs4SGah+uvCm5dqvyRVMbbfGYl22sMPxRiaZkxZ0htZ5xXDv/LP6e0EY+Iz0np1nJvWIlQoR66aczyusgjVpPlTF8DfBQRxdwybz5+AhECjGysv62BxpCLarP7bRYlpc02W4bqF3i; spsc=1774778547689_6382028ec113c3b4605ecf0f0fbf0adc_fZg33dK9zOBI2XTd1-6.XCalEAjqkh679j-gWiugCNcZ; spid=1774778547689_539c201fef3bfae362bb1ce15d5f0a3b_lpi4dwvj7l2eo49g; TS01418b58=0147334a4a22290f6cda4302f7d16b912b7d50ed310ab10a37037f8f2de846e9548f3c6562d63c22b233b66cabaa2673e92fd42df7; _ym_uid=1774778556178935838; _ym_d=1774778556; TS01eb8238=0147334a4abfac71489237665b6e028759c2367d3adaf5d3be6242f2970a38eb64abf058f9ebcf3018f05090d7e58b59b7f1fb5e7a; TS01eb8238028=015905a0a529baaaecec5db2c4c35a8f4bbaf80bd5a456c294b297841131fff871cd5030cd61dd008dc32abaf9dc22f21f262ad1c8",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "https://app.chizhik.club/api/v1/catalog/unauthorized/categories/": {
    "host": "app.chizhik.club",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br, zstd",
    "referer": "https://app.chizhik.club/api/v1",
    "connection": "keep-alive",
    "cookie": "spjs=1774778547689_2cfd8515_013525df_6622b9ae79cabdb51ff75aea00cbf496_c0xZSITEeI/aq35HE2K0gKoK2HUeQVQsqChtRA5ho+p3VnrTnm+8CbSFKcENZkCpdHN33hB7LiaCImfBKcidpdEh1JwYebIjvo9TyxfG6gJPonHotUW5AfyM8EkzwzeOewp+x7JCtgz5+f1UnpCHLhiF/fDsPHB88JUsIT7L4spDd/tTn08DEYAwISwJ6T2V0afUzZ1JXATRIHZMVs1Lk98v0Mz1QFlCTr5CD0f3y7NPaOzBhSAUnfmZWCAnp6a+CnuK1R8QJqlnKZtyHr8zyFZ3W8eu7nJrhyI+dgjY7MEAEXWtDExoY/IiBn57m7+iBhzg6LcHuwPer/JJt+aqFwt/o4sSd25MTehpdGGBxd0cOq7W4gcTL77+H0IMa5GIERW5UZhdVCpWNi9yGorzGzIQ5Ly9WHyVpMHlKDqa68GBIPaIjWgpo78vYksHZrsrbg17iTTAfdYrCuaO1fFE3bgo/EJEdACbPu+Kc5NSsBq/Ya0Bm7klONJTSEef7qKLtjercptLU6TAkCWsGHi68AQXQz9qSj4X06NnTwXj3RR5eJQ9FJUpMo9Oc2k15BogXwt7EYVXoemc/L3nMUHj27v9qfWwNmLpAvJKYzi4VopShfzh3e0gCIEEWMA967kmIDHl3Yl5LVaC8iZeS7vv1wN8oJjENGgV3qnSQjX1sKFNbHDJlG4YHp89mAFEILJYTBv5MKNktw/Lqp9XRU+nq9X32oIef7N49cX5UBz9Mil0Q3fem2q+5/Jy9k+WFkJ6rt8LM2eYLSMPL3LE6RlFfaHSDjZldBlAXL3y+ZNBt43bIf7WsEX2rem5fUQYIDatODfL079PI0qWtmpSDe2RiRUE6OCfnAKmo6N3TxravoZSIfXNmWk9NMCgZEwX14uAf85yu5Y3unPd/n1XuPhIE/zrL8eTZzZe2qJ9t5H1lctOf7owsKcSffUkeYEd7HCJVLHZxb1pkbhUtXhBm+m3F9Gi9Gz65Q5kUaNVfQj4viSQr/LLluc5AtwucUoW5bohHazxyJBkPI/eq0xjYkAmDlsp/EWTYTeM26h/xBvvtwtSJv9ivF0UCdMlfkEbbLiIRCt335JrLwfdY3RvSUmI0BUR1JrOiulW7g8FrEAw7aTIH3HKMQWY8FCsoUXDYjuPiScuRDN08Bs/7ktzB+bmW18BbRWISKIrtip6kxF9wFlVKXyCzGg3I5Evd5wSij8mwqB0zBi5PQzTUnSINrabsX8982qkxikT/b5zwBT3GJBIC/tj4+FmLviqb+axab2FUSp9yi5iFoh0hxvDH+6zCkWFrccaKnYM2GRdT+v+H0fTI/bPGmg+B1GidUs4SGah+uvCm5dqvyRVMbbfGYl22sMPxRiaZkxZ0htZ5xXDv/LP6e0EY+Iz0np1nJvWIlQoR66aczyusgjVpPlTF8DfBQRxdwybz5+AhECjGysv62BxpCLarP7bRYlpc02W4bqF3i; spsc=1774778547689_6382028ec113c3b4605ecf0f0fbf0adc_fZg33dK9zOBI2XTd1-6.XCalEAjqkh679j-gWiugCNcZ; spid=1774778547689_539c201fef3bfae362bb1ce15d5f0a3b_lpi4dwvj7l2eo49g; TS01418b58=0147334a4a22290f6cda4302f7d16b912b7d50ed310ab10a37037f8f2de846e9548f3c6562d63c22b233b66cabaa2673e92fd42df7; _ym_uid=1774778556178935838; _ym_d=1774778556; TS01eb8238=0147334a4abfac71489237665b6e028759c2367d3adaf5d3be6242f2970a38eb64abf058f9ebcf3018f05090d7e58b59b7f1fb5e7a; TS01eb8238028=015905a0a529baaaecec5db2c4c35a8f4bbaf80bd5a456c294b297841131fff871cd5030cd61dd008dc32abaf9dc22f21f262ad1c8",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
