=== Open-Inflation/chizhik_api/tests/__snapshots__/ci.cd/ClassAdvertising.active_inout.schema.json
{
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "background": {
      "type": "string",
      "format": "uri"
    },
    "banner": {
      "type": "null"
    },
    "description": {
      "type": "string"
    },
    "detail": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "msg",
          "title",
          "type"
        ],
        "properties": {
          "msg": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      }
    },
    "end_timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "image": {
      "type": "string",
      "format": "uri"
    },
    "is_thematic": {
      "type": "boolean"
    },
    "logo": {
      "type": "string",
      "format": "uri"
    },
    "pdf": {
      "type": "string",
      "format": "uri"
    },
    "pdf_data": {
      "type": "object",
      "required": [
        "background_color",
        "banner",
        "file",
        "image",
        "subtitle",
        "text_color",
        "title"
      ],
      "properties": {
        "background_color": {
          "type": "string"
        },
        "banner": {
          "type": "null"
        },
        "file": {
          "type": "string",
          "format": "uri"
        },
        "image": {
          "type": "string",
          "format": "uri"
        },
        "subtitle": {
          "type": "string"
        },
        "text_color": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "show": {
      "type": "boolean"
    },
    "start_timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "title": {
      "type": "string"
    },
    "title_color": {
      "type": "string"
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassAdvertising.active_inout.json
{
  "title": "НАДО УСПЕТЬ",
  "description": "Новые товары каждую неделю.\r\nКоличество ограниченно!",
  "image": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/active_inout/Frame_2087325301_ptKUFck.png",
  "background": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/active_inout/Background_in-out_AP6ohw9.png",
  "is_thematic": false,
  "start_timestamp": "2025-08-27T21:00:00Z",
  "end_timestamp": "2025-09-03T20:59:59Z",
  "title_color": "#18181A",
  "logo": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/active_inout_logo/%D0%A7%D0%B8%D0%B6%D0%B8%D0%BA_%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_BS3STRu.png",
  "pdf_data": {
    "title": "КАТАЛОГ НОВИНОК",
    "subtitle": "Товары следующей недели",
    "text_color": "#FFFFFF",
    "background_color": "#18181A",
    "image": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/pdf_image/%D0%BF%D0%B4%D1%84_2_dvZrlX1.png",
    "file": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/pdf_file/%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3_CHIZHIK_36_mobile.pdf",
    "banner": null
  },
  "banner": null,
  "pdf": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/pdf_file/%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3_CHIZHIK_36_mobile.pdf"
}

=== Open-Inflation/chizhik_api/debug.json
{"title": "\u041d\u0410\u0414\u041e \u0423\u0421\u041f\u0415\u0422\u042c", "description": "\u041d\u043e\u0432\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b \u043a\u0430\u0436\u0434\u0443\u044e \u043d\u0435\u0434\u0435\u043b\u044e.\r\n\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u043d\u043e!", "image": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/active_inout/Frame_2087325301_ptKUFck.png", "background": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/active_inout/Background_in-out_AP6ohw9.png", "is_thematic": false, "start_timestamp": "2025-08-27T21:00:00Z", "end_timestamp": "2025-09-03T20:59:59Z", "title_color": "#18181A", "logo": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/active_inout_logo/%D0%A7%D0%B8%D0%B6%D0%B8%D0%BA_%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_BS3STRu.png", "pdf_data": {"title": "\u041a\u0410\u0422\u0410\u041b\u041e\u0413 \u041d\u041e\u0412\u0418\u041d\u041e\u041a", "subtitle": "\u0422\u043e\u0432\u0430\u0440\u044b \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0439 \u043d\u0435\u0434\u0435\u043b\u0438", "text_color": "#FFFFFF", "background_color": "#18181A", "image": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/pdf_image/%D0%BF%D0%B4%D1%84_2_dvZrlX1.png", "file": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/pdf_file/%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3_CHIZHIK_36_mobile.pdf", "banner": null}, "banner": null, "pdf": "https://chizhik.x5static.net/media/backendprod-dpro/catalog/pdf_file/%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3_CHIZHIK_36_mobile.pdf"}
