=== Open-Inflation/chizhik_api/tests/__snapshots__/ci.cd/ClassCatalog.tree.schema.json
{
  "type": "array",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "type": "object",
    "required": [
      "children",
      "depth",
      "icon",
      "id",
      "image",
      "is_adults",
      "is_inout",
      "name",
      "slug"
    ],
    "properties": {
      "children": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "children",
            "depth",
            "icon",
            "id",
            "image",
            "is_adults",
            "is_inout",
            "name",
            "slug"
          ],
          "properties": {
            "children": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "children",
                  "depth",
                  "icon",
                  "id",
                  "image",
                  "is_adults",
                  "is_inout",
                  "name",
                  "slug"
                ],
                "properties": {
                  "children": {
                    "type": "array",
                    "items": {}
                  },
                  "depth": {
                    "type": "integer"
                  },
                  "icon": {
                    "type": "null"
                  },
                  "id": {
                    "type": "integer"
                  },
                  "image": {
                    "type": "null"
                  },
                  "is_adults": {
                    "type": "boolean"
                  },
                  "is_inout": {
                    "type": "boolean"
                  },
                  "name": {
                    "type": "string"
                  },
                  "slug": {
                    "type": "string"
                  }
                }
              }
            },
            "depth": {
              "type": "integer"
            },
            "icon": {
              "type": "string",
              "format": "uri"
            },
            "id": {
              "type": "integer"
            },
            "image": {
              "type": "string",
              "format": "uri"
            },
            "is_adults": {
              "type": "boolean"
            },
            "is_inout": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "slug": {
              "type": "string"
            }
          }
        }
      },
      "depth": {
        "type": "integer"
      },
      "icon": {
        "type": "null"
      },
      "id": {
        "type": "integer"
      },
      "image": {
        "type": "null"
      },
      "is_adults": {
        "type": "boolean"
      },
      "is_inout": {
        "type": "boolean"
      },
      "name": {
        "type": "string"
      },
      "slug": {
        "type": "string"
      }
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ci.cd/ClassCatalog.tree.json
[
  {
    "id": 133,
    "name": "Основной каталог",
    "image": null,
    "icon": null,
    "depth": 1,
    "is_adults": false,
    "is_inout": false,
    "slug": "osnovnoi-katalog",
    "children": [
      {
        "id": 149,
        "name": "НАДО УСПЕТЬ",
        "image": "https://chizhik.x5static.net/media/chizhik-assets/categories/Frame_2087325305_003.png",
        "icon": "https://chizhik.x5static.net/media/chizhik-assets/categories/icon/IMG_Categories_inout.png",
        "depth": 2,
        "is_adults": false,
        "is_inout": true,
        "slug": "nado-uspet",
        "children": [
          {
            "id": 164,
            "name": "Товары предыдущих недель",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "tovary-predydushchikh-nedel",
            "children": []
          }
        ]
      },
      {
        "id": 177,
        "name": "Готовая еда",
        "image": "https://chizhik.x5static.net/media/chizhik-assets/categories/%D0%93%D0%BE%D1%82%D0%BE%D0%B2%D0%B0%D1%8F_%D0%B5%D0%B4%D0%B0_app_2.png",
        "icon": "https://chizhik.x5static.net/media/chizhik-assets/categories/icon/%D0%93%D0%BE%D1%82%D0%BE%D0%B2%D0%B0%D1%8F_%D0%B5%D0%B4%D0%B0_web_old.png",
        "depth": 2,
        "is_adults": false,
        "is_inout": false,
        "slug": "gotovaia-eda",
        "children": [
          {
            "id": 178,
            "name": "Завтраки",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "zavtraki",
            "children": []
          },
          {
            "id": 179,
            "name": "Салаты/Закуски",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "salatyzakuski",
            "children": []
          },
          {
            "id": 180,
            "name": "Вторые блюда/Супы",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "vtorye-bliudasupy",
            "children": []
          },
          {
            "id": 181,
            "name": "Перекусы",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "perekusy",
            "children": []
          }
        ]
      },
      {
        "id": 35,
        "name": "Молочные продукты, яйца",
        "image": "https://chizhik.x5static.net/media/chizhik-assets/categories/Card_1.png",
        "icon": "https://chizhik.x5static.net/media/chizhik-assets/categories/icon/Type%D0%9C%D0%BE%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D0%B5_%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%8B.png",
        "depth": 2,
        "is_adults": false,
        "is_inout": false,
        "slug": "molochnye-produkty-iaitsa",
        "children": [
          {
            "id": 39,
            "name": "Молоко/Сливки",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "molokoslivki",
            "children": []
          },
          {
            "id": 37,
            "name": "Кефир/Ряженка",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "kefirriazhenka",
            "children": []
          },
          {
            "id": 42,
            "name": "Творог",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "tvorog",
            "children": []
          },
          {
            "id": 40,
            "name": "Сметана",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "smetana",
            "children": []
          },
          {
            "id": 38,
            "name": "Масло",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "maslo",
            "children": []
          },
          {
            "id": 167,
            "name": "Маргарин",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "margarin",
            "children": []
          },
          {
            "id": 44,
            "name": "Яйца",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "iaitsa",
            "children": []
          },
          {
            "id": 140,
            "name": "Молочные десерты",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "molochnye-deserty",
            "children": []
          },
          {
            "id": 36,
            "name": "Йогурт",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "iogurt",
            "children": []
          },
          {
            "id": 41,
            "name": "Сырки",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "syrki",
            "children": []
          },
          {
            "id": 43,
            "name": "Творожные десерты",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "tvorozhnye-deserty",
            "children": []
          },
          {
            "id": 134,
            "name": "Мороженое",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "morozhenoe",
            "children": []
          }
        ]
      },
      {
        "id": 100,
        "name": "Сыры и масло",
        "image": "https://chizhik.x5static.net/media/chizhik-assets/categories/Card_2.png",
        "icon": "https://chizhik.x5static.net/media/chizhik-assets/categories/icon/Type%D0%9C%D0%B0%D1%81%D0%BB%D0%BE_%D0%B8_%D1%81%D1%8B%D1%80%D1%8B-min.png",
        "depth": 2,
        "is_adults": false,
        "is_inout": false,
        "slug": "syry-i-maslo",
        "children": [
          {
            "id": 141,
            "name": "Масло",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "maslo",
            "children": []
          },
          {
            "id": 103,
            "name": "Сыры",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "syry",
            "children": []
          },
          {
            "id": 104,
            "name": "Сыры творожные",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "syry-tvorozhnye",
            "children": []
          },
          {
            "id": 101,
            "name": "Сыры плавленые",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "syry-plavlenye",
            "children": []
          },
          {
            "id": 102,
            "name": "Сыры рассольные",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "syry-rassolnye",
            "children": []
          },
          {
            "id": 166,
            "name": "Маргарин",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "margarin",
            "children": []
          }
        ]
      },
      {
        "id": 22,
        "name": "Крупы и макароны",
        "image": "https://chizhik.x5static.net/media/chizhik-assets/categories/Card_3_d4RRoyE.png",
        "icon": "https://chizhik.x5static.net/media/chizhik-assets/categories/icon/Type%D0%AC%D0%90%D0%9B__%D0%90%D0%93%D0%9B-min.png",
        "depth": 2,
        "is_adults": false,
        "is_inout": false,
        "slug": "krupy-i-makarony",
        "children": [
          {
            "id": 24,
            "name": "Крупы",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "krupy",
            "children": []
          },
          {
            "id": 25,
            "name": "Макароны",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "makarony",
            "children": []
          },
          {
            "id": 27,
            "name": "Сухие завтраки, мюсли",
            "image": null,
            "icon": null,
            "depth": 3,
            "is_adults": false,
            "is_inout": false,
            "slug": "sukhie-zavtraki-miusli",
            "children": []
          },
          {
            "id": 23,
